### ISSUE TITLE
关于打包asar的建议

### ISSUE THREAD

**Issue by zxp19821005** [pokon548/chengla-for-linux#5]
如题。我已经将该程序移植到了ArchLinux的AUR (https://aur.archlinux.org/packages/chengla-linux-unofficial-bin)
因为Electron的体积比较大，所以打包的时候使用了系统的Electron。
程序可以正常运行，但是运行后在任务栏图标显示为无图标的状态。
我通过asar解压了app.asar，但是在解压后的目录中并没有发现png或者svg文件。
希望在新版本打包的时候能够加入图像文件，解决程序运行时在任务栏无法正常显示图标的问题。
谢谢！

**Comment by pokon548** [comment]
感谢反馈。该问题已尝试在 `1.0.8` 修复。目前是 `pre-release` 阶段，如果测试无问题的话我会标记为正式版：https://github.com/pokon548/chengla-for-linux/releases/tag/v1.0.8
新版本的逻辑是：
- 如果处于开发阶段，直接引用 `build/icon.png`；
- 如果程序已被打包为二进制文件，则引用资源文件下的图标文件 `icon.png` （如果是拆二进制包，你将在`resources`目录下看到这个图标），该图标由程序打包时自动引入。

在我这边测试时，两种情况下程序均可正常在任务栏显示图标。如有问题可继续反馈 :)

**Comment by zxp19821005** [comment]
目前已经正常，任务栏图标可以显示。但是通过终端运行时，能够发现错误日志：
```
$ chengla-linux-unofficial
/usr/lib/electron27/resources
```
我怀疑可能是相对路径指定的有问题。

**Comment by pokon548** [comment]
> 目前已经正常，任务栏图标可以显示。但是通过终端运行时，能够发现错误日志：
> 
> ```
> $ chengla-linux-unofficial
> /usr/lib/electron27/resources
> ```
> 
> 我怀疑可能是相对路径指定的有问题。

放进源码里的 `console.log` 忘删了，感谢提醒。稍后会上传没有打印日志的版本（
Edit: 不会影响正常使用。

**Comment by zxp19821005** [comment]
好的，谢谢！
